{
  try {
    this.fault.setFaultString(reason);
  }
 catch (  SOAPException e) {
    throw new RuntimeException("Error creating fault message.",e);
  }
  return this;
}
