{
  InitialContext authCtx=null;
  try {
    if (password == null || password.isEmpty()) {
      throw new AuthenticationException("Empty password used");
    }
    Hashtable<String,Object> env=new Hashtable<String,Object>(this.connectionProperties);
    env.put(Context.SECURITY_AUTHENTICATION,LDAPConstants.AUTH_TYPE_SIMPLE);
    env.put(Context.SECURITY_PRINCIPAL,dn);
    env.put(Context.SECURITY_CREDENTIALS,password);
    env.put("com.sun.jndi.ldap.connect.pool","false");
    authCtx=new InitialLdapContext(env,null);
  }
 catch (  AuthenticationException ae) {
    if (logger.isDebugEnabled()) {
      logger.debugf(ae,"Authentication failed for DN [%s]",dn);
    }
    throw ae;
  }
catch (  Exception e) {
    logger.errorf(e,"Unexpected exception when validating password of DN [%s]",dn);
    throw new AuthenticationException("Unexpected exception when validating password of user");
  }
 finally {
    if (authCtx != null) {
      try {
        authCtx.close();
      }
 catch (      NamingException e) {
      }
    }
  }
}
