{
  try {
    return method.invoke(em,args);
  }
 catch (  InvocationTargetException e) {
    throw convert(e.getCause());
  }
}
